### PR TITLE
Add PR to EBoard Tags

### PR DESCRIPTION
**Pull request by jabbate19**

### CODE REVIEW

**Review by mxmeinhold — CHANGES_REQUESTED** [review]
Do you need to add a badge css? https://github.com/ComputerScienceHouse/packet/blob/develop/frontend/scss/components/badges.scss

**Comment by jabbate19** [comment]
No, it falls under the Eboard tag

**Comment by Mstrodl** [comment]
> Do you need to add a badge css? https://github.com/ComputerScienceHouse/packet/blob/develop/frontend/scss/components/badges.scss

No:
```css
    &.badge-eboard {
        color: #fff;
        background-color: #4CAF50;
    }
```

**Comment by mxmeinhold** [comment]
Double checking a couple other things, since this was a while ago. Are you able to run a build on packet-dev, or do you want me to?

**Comment by jabbate19** [comment]
I haven't done it before and don't have access. Can you run it if you have time?

**Review by mxmeinhold — APPROVED** [review]
Merging to develop, then let's figure out if doing a deploy or if we're trying to resolve the admin issues

**Pull request merged**
