### PR TITLE
Hide sigs from frosh and sort by names by default

### PR DESCRIPTION
**Pull request by mxmeinhold**
@crigney3 please review

Still need to test things on dev, but this is the preliminary so I can toss it on OKD

### CODE REVIEW

**Review by Dr-N0 — APPROVED** [review]
LGTM, also pulled and worked so 👍

**Review by galenguyer — APPROVED** [review]

**Comment by mxmeinhold** [comment]
Small regression: in active packets list, for onfloors, the row background for where the sign button would be is not the right color.
image

**Comment by mxmeinhold** [comment]
Linting should be fixed by #285

**Comment by mxmeinhold** [comment]
## Screenshots!

new frosh active packets view, now missing signature counts
^ in the most recent update, this is sorted alphabetically, rather than reverse alphabetically.

new frosh packet view
^ this should display nothing for off floor frosh, I should probably disable the links altogether, though I still need to check this.

**Comment by galenguyer** [comment]
Rebasing to pull in pylint fixes, then will squash before merging.

**Comment by mxmeinhold** [comment]
I don't think i'm going to get to fixing that regression today. Any objection to me just merging? Regression doesn't actually hinder signing a packet, you just have to click into the packet.

**Comment by galenguyer** [comment]
LG(Enough)TM

**Pull request merged**
